### ISSUE TITLE
Error when running cron job

### ISSUE THREAD

**Issue by skeet** [miyagawa/hubot-cron#24]
I'm getting an error after setting up a new cron job via Slack. It's set up to send messages to a public room called #development.

e.g: 
```
hubot new job 0 10 * * 1-5 "It's time for standup, folks!"

458293: 0 10 * * 1-5 @C033R5PHW "It's time for standup, folks!"
```

The job worked fine for a few days but now I can see the following error in the logs:

```
2015-02-05T10:00:00.802614+00:00 app[web.1]: Sending message
2015-02-05T10:00:01.575453+00:00 app[web.1]: Slack services error: 500
2015-02-05T10:00:01.575612+00:00 app[web.1]: Invalid channel specified
```

Any idea how I can resolve this?

Thanks.

**Comment by skeet** [comment]
Quick update:

I've not seen the "Invalid channel" error since prepending a hash to the room ID:

cron.coffee
```
sendMessage: (robot) ->
    envelope = user: @user, room: "#" + @user.room
    robot.send envelope, @message
```

Happy to make a PR if you think it's an issue.

**Comment by miyagawa** [comment]
well if you do that it will break all other adapters.

**Comment by skeet** [comment]
Your plugin doesn't work for Slack then.

**Comment by miyagawa** [comment]
But in OP you said it works sometimes but sometimes doesn't? Can you spot the difference?

**Comment by skeet** [comment]
Working "sometimes" makes it a completely non-viable option for Slack.

**Comment by miyagawa** [comment]
@skeet geez, I meant: if you can tell the difference when it works and when it doesn't, we can figure out a fix to make it work. Blindly adding '#' makes all adapters fail (and often fails on Slack, assuming the original code sometimes works).

**Comment by miyagawa** [comment]
I looked at the slack adapter and this change looks suspicious:
https://github.com/slackhq/node-slack-client/commit/9b454122951c5064624881de302f7f00f816e853

**Comment by skeet** [comment]
Ok apologies, I misunderstood.

I agree that looks suspicious. I'm not familiar at all with how the Slack client works though I do believe all public Slack channels should start with a hash.

**Comment by miyagawa** [comment]
@skeet can you note the versions of node-slack-client and hubot-slack you're currently using?

Apparently the issue is not released to npm yet on the node-slack-client/hubot-slack side, and I hope it gets fixed once they're shipped...

**Comment by skeet** [comment]
hubot-slack: 2.2.0

I don't think I can get the version of node-slack-client as we connect to hubot via the Slack admin interface as an integration and I don't get any version information.

Yeah, let's hope so.

Cool, thanks for your help.

**Comment by miyagawa** [comment]
> I don't think I can get the version of node-slack-client as we connect to hubot via the Slack admin interface as an integration and I don't get any version information.

Hm, not sure if it's relevant :) I guess you can get the version by looking at: 
`node_modules/hubot-slack/node_modules/slack-client/package.json`

**Comment by skeet** [comment]
Ah, version 2.2.0 doesn't have any dependencies hence why I couldn't find it!

https://github.com/slackhq/hubot-slack/blob/2.2.0/package.json

**Comment by miyagawa** [comment]
Aha, interesting. Thanks for checking :)

**Comment by tvmanikandan** [comment]
I am using slack adapter. Please confirm how to use your module with slack adapter.

**Comment by tvmanikandan** [comment]
skeet:
How did you create the below command:

**Comment by tvmanikandan** [comment]
skeet:,
How did you create the below command:
hubot new job 0 10 * * 1-5 "It's time for standup, folks!"

I am running the below command to invoke hubot , but then not able to figure out to create cron command like above.

my usage model:
bin/hubot -a slack => Loads all .js and .coffee files in scripts directory.

-Mani

**Comment by tvmanikandan** [comment]
where do I find about creating hubot rooms, getting hubot  room details , getting hubot users list ? Please let me know.

-mani

**Comment by skeet** [comment]
@tvmanikandan I can run it locally just with:
```
bin/hubot
```

Then:
```
hubot> hubot new job 0 10 * * 1-5 "It's time for standup, folks!"
Job 867617 created
```

You maybe just have to follow the specific instructions for Slack? https://github.com/slackhq/hubot-slack
