### ISSUE TITLE
Configure default timezone

### ISSUE THREAD

**Issue by mwarkentin** [miyagawa/hubot-cron#28]
After using this plugin for a few days (awesome, btw!) - a recurring pattern on every job is to update the timezone to our local timezone. It would be really nice to be able to configure a default tz for every job that's created (although you could still override manually).

I was thinking this could be done by setting a `HUBOT_CRON_DEFAULT_TZ` environment variable. If this is set, during job creation, it could just call out to the update tz method automatically.

**Comment by miyagawa** [comment]
Yes, the default timezone can be set by setting `TZ=` environment variable on the node process (such as `TZ=America/Los_Angeles`), and each job can have its own timezone per #20.

**Comment by mwarkentin** [comment]
Oohh, awesome. Might be worth adding something to the docs about that.

Thanks!

**Comment by miyagawa** [comment]
the latter is already in the docs.

**Comment by mwarkentin** [comment]
Yep, we were already using the manual method - just thought some docs about configuring the default tz could be helpful. I can open a PR for it if you want.
